version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          DATABASE_URL: postgresql://postgres:secret@localhost:5432/ruby-pg-extras-test
      - image: circleci/postgres:11.5
        command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ruby-pg-extras-test
          POSTGRES_PASSWORD: secret
    parallelism: 1
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: sudo apt-get update
      - run: sudo apt install postgresql-client-11
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run specs
          command: |
            bundle exec rspec spec/
workflows:
  version: 2
  test:
    jobs:
      - test
